apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: mr08rvo4h-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-25dac6ac69.7v0q.p3.openshiftapps.com/rhtap/rhtap-qe:9eb20b7918bc632c84b0f152ab355eeb00a0bd11@sha256:36c4fdb80b2df9b2d19d893b38fc84d40ca472effe2e5331d27c148ea2e331ee
        name: container-image  
